---
title: "EDLD 652 Final Project Draft"
author: "Adriana Conn"
date: "2023-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(haven)
library(Hmisc)
library(ggplot2)
library(dplyr)
library(viridis)
library(outliers)
library(EnvStats)
library(datarium)
library(car)
library(graphics)
library(tidyverse)
```

```{r load data}
d <- read_sav("~/Documents/PhD/2022-2023/Coursework/Winter 2023/EDLD 652/Final Project/final_project_draft/data/ACE_TEI_Health_Study_1.sav")
```

```{r exploratory data analysis}
# summary
summary(d)

# standard dev of aces
sd(d$ACE)

# variance for aces
var(d$ACE)

# st dev for emotional intelligence
sd(d$TEI)

# variance for ei
var(d$TEI)

# st dev for health
sd(d$Health)

# variance for health
var(d$Health)

# correlation between all variables in dataset (show p values)
all_corr <- rcorr(as.matrix(d))
round(all_corr$P, 3)

# correlation between ACEs and EI
ACE_EI_corr <- cor.test(d$ACE, d$TEI)
ACE_EI_corr
format(ACE_EI_corr, scientific = FALSE)

# ACEs and EI are moderately negatively correlated.

# correlation between ACEs and health
ACE_Health_corr <- cor.test(d$ACE, d$Health)
ACE_Health_corr
format(ACE_Health_corr, scientific = FALSE)

# ACEs and health are moderately negatively correlated.

# correlation between EI and health
EI_Health_corr <- cor.test(d$TEI, d$Health)
EI_Health_corr
format(EI_Health_corr, scientific = FALSE)

# EI and health are moderately positively correlated.

# correlation between ACEs and depression, anxiety, stress
ACE_DASS_corr <- cor.test(d$ACE, d$DASS)
ACE_DASS_corr
format(ACE_DASS_corr, scientific = FALSE)

# correlation between ACEs and SES
ACE_SES_corr <- cor.test(d$ACE, d$SES)
ACE_SES_corr
format(ACE_SES_corr, scientific = FALSE) # not significantly correlated

# checking assumptions for t-test, outliers, first boxplot for ACEs
boxplot(d$ACE,
        ylab = "ACE")

boxplot.stats(d$ACE)$out

out <- boxplot.stats(d$ACE)$out
out_ind <- which(d$ACE %in% c(out))
out_ind

d[out_ind, ]

test <- rosnerTest(d$ACE,
  k = 2
)
test

test$all.stats

# No outliers for ACEs variable

# checking outliers for TEI variable
boxplot(d$TEI,
        ylab = "TEI")

boxplot.stats(d$TEI)$out

out_TEI <- boxplot.stats(d$TEI)$out
out_ind_TEI <- which(d$TEI %in% c(out))
out_ind_TEI

d[out_ind_TEI, ]

test2 <- rosnerTest(d$TEI,
  k = 1
)
test2

test2$all.stats

# no outliers for TEI

# check normality for ACE

ggplot(d, aes(ACE)) +
  geom_histogram(binwidth = 1) +
  theme_bw()

# check normality for TEI
ggplot(d, aes(TEI)) +
  geom_histogram() +
  theme_bw()

# check equality of variances
leveneTest(y = d$ACE, group = d$sex)

# can assume equality of variances!

# t test for sex and ACEs
test_sex_ace <- t.test(ACE ~ sex, data = d)
test_sex_ace

# sex and aces not siginficantly related.

#check equality of variances for TEI
leveneTest(y = d$TEI, group = d$sex)

# can assume equality of variances!

# t test for sex and TEI
test_sex_TEI <- t.test(TEI ~ sex, data = d)
test_sex_TEI

# sex and tei not significantly related.

# correlation between tei and ses
TEI_SES_corr <- cor.test(d$TEI, d$SES)
TEI_SES_corr
format(TEI_SES_corr, scientific = FALSE)

# weak to moderate correlation between SES and TEI!

# correlation between SES and health
SES_Health_corr <- cor.test(d$SES, d$Health)
SES_Health_corr
format(SES_Health_corr, scientific = FALSE)

# not significantly correlated.

library(tidyverse)
library(graphics)
```

```{r plot 1}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(viridis)
library(RColorBrewer)

d$sex <- as.factor(d$sex)

ACE_TEI_plot <- d %>%
  ggplot(aes(ACE, TEI)) +
  geom_point(aes(color = sex)) +
  scale_color_manual(name = "Sex", labels = c("Female", "Male"), values = c("#F05039", "#7CA1CC")) +
  geom_smooth(method = "lm", se = FALSE, col = "black") +
  labs(x = "Adverse Childhood Experiences (ACEs)", y = "Trait Emotional Intelligence (TEI)",
       title = "Association Between Exposure to ACEs and Trait Emotional Intelligence Among a Sample of Adults",
       subtitle = "As exposure to ACEs increases, TEI decreases",
       caption = "Sex is not significantly related to ACEs or TEI") +
  theme_minimal()

ACE_TEI_plot + scale_x_continuous(breaks=seq(0,9,by=1))
  
# need to figure out changing y axis labels
summary(d)

# ***PREDICTOR NEEDS TO BE ON X AXIS***
```

```{r plot 2}
ACE_Health_plot <- d %>%
  ggplot(aes(ACE, Health)) +
  geom_point(aes(color = sex)) +
  scale_color_manual(name = "Sex", labels = c("Female", "Male"), values = c("#F05039", "#7CA1CC")) +
  geom_smooth(method = "lm", se = FALSE, col = "black") +
  labs(x = "Adverse Childhood Experiences (ACEs)", y = "Self-Reported Health",
       title = "Association Between Exposure to ACEs and Self-Reported Health Among a Sample of Adults",
       subtitle = "As exposure to ACEs increases, health decreases") + 
  theme_minimal()

ACE_Health_plot + scale_x_continuous(breaks=seq(0,9,by=1))

# try to change sex to ses
```

```{r run regression for plot 3}
reg <- lm(cbind(TEI, Health) ~ ACE, data = d)
summary(reg)
# regression is significant!

# linear regression for interactions

library(tidyverse)

linreg <- lm(Health ~ ACE + TEI, data = d)
summary(linreg)

# linear regression is significant!

# interaction

int <- lm(Health ~ ACE*TEI, data = d)
summary(int)

# model equation: 
# Health = 2.4 - 0.33*ACE + 0.95*TEI
```

```{r plot 3}
library(ggplot2)

library(ggeffects)
library(ggforce)

library(ggiraphExtra)

int_plot<- ggPredict(int, interactive = TRUE)

int_plot 
```

